model_type: "GCN"
hidden_dim: 64
dropout: 0.2
normalization: "NodesAndEdges"

batch_size: 64
learning_rate: 0.001
weight_decay: 0.0001
epochs: 50
earlystop: 10

train_ratio: 0.70
val_ratio: 0.15
threshold: 0.5
pos_weight: "auto"
seed: 42

task: "edge_classification"
device: "cuda"

graph_path: "/lustre/ific.uv.es/ml/uovi156/data/graphs/l1nano_graphs_prod/S1"
graph_name: "l1nano_dataset_1.pt"
out_model_path: "/lhome/ext/uovi156/uovi1564/results_edge_cls/S1"
save_tag: "edge_cls_GCN_50epochs"

num_files: 1
do_train: true
do_validation: true
do_test: true
